### PR TITLE
Create 10164.md (What's new in Swift) 

### PR DESCRIPTION
**Pull request by kyaw-codes**

### CODE REVIEW

**Comment by Jeehut** [comment]
@kyaw-codes Thank you for providing this! Merging. 🎉 

Next time, please note that you can leave the title out, too. It's all added automatically by the process Federico had created for the project. I'll remove it after merge. 💯

**Comment by kyaw-codes** [comment]
@Jeehut Got cha!

**Comment by rogerluan** [comment]
@kyaw-codes @Jeehut just a heads up that the formatting got messed up in the live website 😬 https://wwdcnotes.com/notes/wwdc23/10164/

image

**Comment by Jeehut** [comment]
@rogerluan Feel free to provide a PR with a fix, currently in the middle of a session

**Pull request merged**
