### PR TITLE
FIXED 10086.md

### PR DESCRIPTION
**Pull request by multitudes**
done update 10086 usd ecosystem

### CODE REVIEW

**Review by Jeehut — APPROVED** [review]
Thank you for the shortened notes, much better!

The "We" perspective is a little better than the "I", but I personally prefer the notetaker's perspective, so long term (or for new notes) let's try to have no perspective or the community's one. But a great first step! 👍

**Comment by multitudes** [comment]
> Thank you for the shortened notes, much better!
> 
> The "We" perspective is a little better than the "I", but I personally prefer the notetaker's perspective, so long term (or for new notes) let's try to have no perspective or the community's one. But a great first step! 👍

Thanks! I removed quite a lot of text. I can see that is definitely a good thing. I sometimes tried to use the passive form. I will think about how to remove more of the 'we's further ...  Let's say if I see a sentence like, "we think you gonna love it" then I would just nuke it 💣 

But in case of " to use this api we need to implement this..."  then is the 'we' a community one? Of course I can do "to use this api x needs to be implemented"...

So yeah I am working on this. :)

**Comment by Jeehut** [comment]
I don't have a strong opinion here, but just a second opinion, I personally would try to group everything that fits into one idea like in "to use API X we need to implement function Y" into a list of things to mention. Then I simply state something like: "Implementation functions: Y, Z, ..."

But I'm one of those who like to keep notes really short. If I had the time, I would add links to the types or protocols or functions and even skip their parameters etc. (often there are many overloads anyways). I personally never write full sentences in note-taking. I think a bit like I'm writing 10 tweets per session. 😅

**Comment by multitudes** [comment]
yes I understand. My notes are getting shorter as well (slowly :) 

What I noticed yesterday updating the macro session. The presenter goes through the steps to create a macro in Xcode and I have a step by step note with screenshot at every step. If I would not take so many screenshots, if I wanted to make a macro I would have to watch the video. Now I can just go back to the note and see the screenshots and see , ah ok he updated the plist there... 
but having those screenshots also make the descriptions more difficult to shorten. To kind of know where I am when I insert the screenshot I insert a sentence to help me out. And there sometimes there is not much to guess or to rephrase because it goes like a tutorial, so I would use the pronoun 'we' in this case because it is we in the developers who are supposed to do it. 🤔 (I think)

Sometimes I like to add screenshots because I realised that visually it helps to distinguish between sessions. So I would remember, ah that was the sessions where they showed that animation... for instance. Or it is just funny to see that the wwdc22 was all about a pancake van stationed in Cupertino 😂

But I hear you! 
and I am removing a lot of descriptions, because the less we need to read the faster we get to the point of the session! 👍

**Comment by Jeehut** [comment]
I see. I'm not sure if it's really valuable long-term (or short-term) to preserve the "ahh, this was that session" feeling or the jokes the engineers make. I personally would argue it's not. Also, I remember that Federico always preferred to have code examples directly inside three backticks which is better both for copy & paste and for screenreaders. So, if your screenshot only shows a step where code is added, you could instead just copy & paste the code. But if a screen or animation is shown, obviously an image is more useful.

**Comment by multitudes** [comment]
Ah yes, and no the jokes are all removed :) I try now to remove as much as I can including everything not essential to the narrative... Including the images of the pancakes was perhaps not needed, but it is only one screenshot out of 20 maybe? 

and yes I put all code in backticks. When the code is in a screenshot it will be in backticks too for easy copy and paste and I would keep the screenshot only if a preview is shown like in swiftui.

Yeah definitely a work in progress. 

I am working now to add a new note about swift charts wwdc22. Here I tried to add as many charts screenshots as I could while keeping the narrative to a minimum. I even collated for screenshots into one to get one screenshot instead of 4. There is almost no code but I thought that the point of the session in particular was to be inspired and see charts examples. I will send it later today, so maybe you can take a look and say what do you think...

**Comment by multitudes** [comment]
For instance this is made out of 4 different screenshots...
image

**Pull request merged**
