### PR TITLE
some cosmetic spacing in 10043 and adding 10157 - animations and with maps too!

### PR DESCRIPTION
**Pull request by multitudes**
10043 Meet MapKit for SwiftUI had some code formatting problems. I added extra spaces between the code blocks.

And I add adding 10157 - Wind your way through advanced animations in SwiftUI

### CODE REVIEW

**Review by multitudes — COMMENTED** [review]
Just added blank spaces...

**Review by Jeehut — APPROVED** [review]
@multitudes Thank you very much for both! Merging. 🎉

**Comment by multitudes** [comment]
Thanks! Happy to help. The content/notes/wwdc23/10157.md is done but the page doesn't show it. The title is "Wind your way through advanced animations in SwiftUI" ...

**Comment by Jeehut** [comment]
@multitudes My bad, CI was offline, just started it, notes should be up in a couple of minutes!

**Comment by Jeehut** [comment]
@multitudes Something in 10043.md breaks RSS validation. The code where it breaks looks like this in RSS `</code></pre>]]>` which makes me believe it could be related to some code sample, but I have no idea. Just wanted to let you know why the deployment still didn't work...

**Comment by multitudes** [comment]
@Jeehut Thanks for the hint. It could be a bad line break. I switched on the invisibles in Xcode and found some hidden spaces (?) character just before a block of code. I then rechecked my other notes but only the 10043 had this problem. So I send another pull request now. Thanks!

**Comment by Jeehut** [comment]
The feed being validated is only on my CI, I don't think it gets uploaded. But if you want to elaborate yourself, here's the full file contents. It fails with "line 941, column 16: Invalid character in a URI":

https://gist.github.com/Jeehut/58902d5739bd42c8e39a9a6f4cc24948

**Comment by multitudes** [comment]
@Jeehut  It is exactly where my note is ending. 
The note is the "Meet Apple Server API" and the text I see is an old version of the file. Since then I removed those pictures and links. It is weird that the link ends like `[compass3]: https://www.wwdcnotes.com/images/notes/wwdc23/10043/compass3.j` and one .jpg
Screenshot 2023-07-28 at 10 41 39

but the link above is not in the original file anymore. So the engine is not rendering new HTML. The file in question is the 10006.md in the 2022 folder which ends like this now
Screenshot 2023-07-28 at 11 00 38
with the last line being `[exceedingq]: ../../../images/notes/wwdc22/10006/exceedingq.jpg`

The change in the 10006 file is not recent, probably a week old. Since then I made many changes to the 10043 in 2023 trying to fix the code not displaying correctly which have not been rendered either. 

Can you pls force pre-render the html?

**Comment by Jeehut** [comment]
@multitudes No idea how to do that. Maybe I can play around when I have more time. I'm quite busy now...

**Comment by multitudes** [comment]
@Jeehut Sure I totally understand.  Do it sometimes when you can :) 

What I meant is from my side there is nothing I can do (I believe), because the changes in the .md source files are not being reflected in the HTML. 

I could prepare a few more notes this weekend. I am watching those videos anyway! So I could put them in the pipeline for later 👍

**Pull request merged**
