### PR TITLE
Update 10167.md

### PR DESCRIPTION
**Pull request by japanese-goblinn**
Fixed a few typos

### CODE REVIEW

**Comment by japanese-goblinn** [comment]
I've noticed that last table is not rendered correctly on web page. It might be that one symbol that've fixed in last commit but I'm not entirely sure
image

**Review by Jeehut — APPROVED** [review]
@japanese-goblinn Thank you very much! Merging. 🎉

**Comment by japanese-goblinn** [comment]
@Jeehut I've checked and last table is still not rendered correctly. Can you check what is causing a problem or maybe there a way to build site locally so I can tweak things a bit to resolve this?

**Comment by Jeehut** [comment]
@japanese-goblinn Unfortunately there is no way of building this locally. I will certainly change that next year. All I can say is that Publish from John Sundell is used internally to render the site, so you might find help there. 🤷🏻‍♂️

**Comment by japanese-goblinn** [comment]
@Jeehut thanks. see what i can do

**Pull request merged**
