### PR TITLE
Added a bonus Xcode 14 feature

### PR DESCRIPTION
**Pull request by Shaurya50211**

### CODE REVIEW

**Comment by zntfdr** [comment]
Hi! Thank you for the PR 😃

Would it be possible to update the video with clearer examples?

E.g.

if 6 == 7 {
  if true {
    ..

(The current example shows assignments used as conditions)

Thank you!

**Comment by Shaurya50211** [comment]
Thanks for the feedback, I am working on it

**Comment by Shaurya50211** [comment]
Updated it, are the examples okay or should I try something different?

**Comment by zntfdr** [comment]
Perfect, thank you very much 😊

**Pull request merged**
