### PR TITLE
Added an image to 10014.md

### PR DESCRIPTION
**Pull request by Shaurya50211**

### CODE REVIEW

**Comment by Jeehut** [comment]
Thank you for your contribution. Please follow the guidelines on how to add images, see here, then I will happily merge:
https://github.com/WWDCNotes/Content/blob/main/CONTRIBUTING.md#where-to-save-the-note-images

**Comment by Shaurya50211** [comment]
> Thank you for your contribution. Please follow the guidelines on how to add images, see here, then I will happily merge: https://github.com/WWDCNotes/Content/blob/main/CONTRIBUTING.md#where-to-save-the-note-images

Thank you for the response I will work on it and update my pull request

**Comment by Shaurya50211** [comment]
So do I just add a description for the image? For e.g. description

**Comment by Shaurya50211** [comment]
@Jeehut I had another question, do you know where I can find the documentation on Xcode 15 so I can maybe add more stuff in it

**Comment by Shaurya50211** [comment]
Sorry for the confusion I meant if there is a file which has new feautres of xcode 15 like on content/notes/wwdc22/110427.md

**Comment by Jeehut** [comment]
@Shaurya50211 I'm not sure if you linked to the right one. How could a WWDC 22 session have Xcode 15 content which was released in 2023? I'm still a bit confused what you mean.

**Pull request closed without merging**
