### PR TITLE
Add Dive into App Intents [WWDC22]

### PR DESCRIPTION
**Pull request by Jeehut**
Notes taken while live streaming on https://www.twitch.tv/Jeehut.
Watch later here: https://www.youtube.com/playlist?list=PLvkAveYAfY4SNTrJb_WugjkbBzg_YjyP4.

### CODE REVIEW

**Comment by zntfdr** [comment]
Thank you for all the notes!

I'm looking forward to a wide-spread adoption of app intents 🤩

**Comment by Jeehut** [comment]
@zntfdr Sure, hope they are useful. Unfortunately, they seem not to render correctly. I will try to take my todays and tomorrows notes with sections (`##`) etc. right away, maybe that'll help. Still no time to do much other than copy & paste things, so much to watch / videos to cut / Twitter engagements etc. going on this week. 😆

**Comment by zntfdr** [comment]
@Jeehut I should have fixed most things in https://github.com/WWDCNotes/Content/pull/247 (deployed about 2h ago), do you still see render glitches? Maybe Safari has an old version cached (sometimes I need to refresh the note webpage to see the newer version)

**Comment by Jeehut** [comment]
@zntfdr Oh, no, looking good now. I didn't check after your fixes. Thank you! 👍

**Pull request merged**
